
---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp1-suxess-it-dev
  labels:
    app : myapp1
    team: group:default/team-a
    build-namespace: myapp1-build
    size: medium
    environment: suxess-it-dev
#    goldilocks.fairwinds.com/enabled: "true"

---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp1-suxess-id-qa
  labels:
    app : myapp1
    team: group:default/team-a
    build-namespace: myapp1-build
    size: medium
    environment: suxess-id-qa
#    goldilocks.fairwinds.com/enabled: "true"

---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp1-suxess-it-prod
  labels:
    app : myapp1
    team: group:default/team-a
    build-namespace: myapp1-build
    size: medium
    environment: suxess-it-prod
#    goldilocks.fairwinds.com/enabled: "true"

