apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: myapp1
  description: myapp1
  labels:
    size: medium
    environments: suxess-it-dev-suxess-id-qa-suxess-it-prod
spec:
  owner: group:default/team-a